[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: blob:;
      style-src 'self' 'unsafe-inline' https: http:;
      img-src 'self' data: blob: https: http:;
      font-src 'self' https: http: data:;
      connect-src 'self' https: http: ws: wss:;
      frame-src 'self' https: http:;
      media-src 'self' https: http: blob:;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https:;
      frame-ancestors 'self';
      """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
