export const ROLE_PERMISSIONS = {
  "super-admin": {
    label: "Super Admin",
    color: "bg-purple-600",
    description: "Full access to all features, including managing admins and permissions",
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: true,
    canCloneEvents: true,
    canDisableEvents: true,
    canManageUsers: true,
    canViewAnalytics: true,
    canManageAdmins: true,
    canEditPermissions: true,
    canBeModified: false,
    canAccessMarketing: true
  },
  "admin": {
    label: "Admin",
    color: "bg-red-500",
    description: "Full access to all features except admin management",
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: true,
    canCloneEvents: true,
    canDisableEvents: true,
    canManageUsers: true,
    canViewAnalytics: true,
    canManageAdmins: false,
    canEditPermissions: false,
    canBeModified: true,
    canAccessMarketing: true
  },
  "marketing-supervisor": {
    label: "Marketing Supervisor",
    color: "bg-yellow-500",
    description: "Can create, edit, clone, disable and delete events",
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: true,
    canCloneEvents: true,
    canDisableEvents: true,
    canManageUsers: false,
    canViewAnalytics: true,
    canManageAdmins: false,
    canEditPermissions: false,
    canBeModified: true,
    canAccessMarketing: true
  },
  "marketing": {
    label: "Marketing",
    color: "bg-blue-500",
    description: "Can create, edit, clone and disable events",
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: false,
    canCloneEvents: true,
    canDisableEvents: true,
    canManageUsers: false,
    canViewAnalytics: false,
    canManageAdmins: false,
    canEditPermissions: false,
    canBeModified: true,
    canAccessMarketing: true
  },
  "marketing-intern": {
    label: "Marketing Intern",
    color: "bg-green-500",
    description: "Can edit and clone events only",
    canCreateEvents: false,
    canEditEvents: true,
    canDeleteEvents: false,
    canCloneEvents: true,
    canDisableEvents: false,
    canManageUsers: false,
    canViewAnalytics: false,
    canManageAdmins: false,
    canEditPermissions: false,
    canBeModified: true,
    canAccessMarketing: true
  }
};